language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - phpenv config-add ./app/config/php.ini
  - composer install --prefer-source

script:
  - ./bin/phpspec run --format=pretty
  - ./bin/phpunit --printer PHPUnit_Util_TestDox_ResultPrinter_Text
  - php ./coverage-checker.php ./var/logs/clover.xml 50
  - cat ./var/logs/clover.xml
  - ./bin/phpcpd -vvv --log-pmd="./var/logs/cpd.xml" ./src
  - ./bin/phpmd ./src text ./app/config/ruleset.xml

after_script:
  - ./bin/coveralls -v
  - cat ./var/logs/coveralls-upload.json
