language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - composer install --prefer-source

script:
  - ./bin/phpspec run --format=pretty
  - ./bin/phpunit --printer PHPUnit_Util_TestDox_ResultPrinter_Text
  - php ./coverage-checker.php ./var/logs/clover.xml 50
  - cat ./var/logs/clover.xml

after_script:
  - ./bin/coveralls -v
  - cat ./var/logs/coveralls-upload.json
